### ISSUE TITLE
Provide @types for Typescript

### ISSUE THREAD

**Issue by LucasBrazi06** [jarden-digital/react-native-recaptchav3#2]
I migrated my react-native project to Typescript and got this error:

![image](https://user-images.githubusercontent.com/25266945/65339995-89e86c00-dbcd-11e9-965b-7794461ac730.png)

Is it possible to provide these types?
Thanks!

**Comment by Haskkor** [comment]
Hi,

Interesting...as you can see, my library is written in TypeScript and the compilation creates the d.ts files. 
I'll investigate but I don't know what to tell you at this stage.

Cheers,
Jeremy
