### ISSUE TITLE
APP did not get any responses from JSX.Element

### ISSUE THREAD

**Issue by DenisSokoloff** [jarden-digital/react-native-recaptchav3#4]
**Tested on Android Emulator and Android Device**

I fill correct data of recaptchav3 from working site
But did not any responses. App works w/o warning and errors

```
            <>
                <Button onPress={() => this._captchaRef.refreshToken()}>
                    <Text style={{color:'#FFF'}}>Retry</Text>
                </Button>
                <ReCaptchaV3
                    ref={(ref: ReCaptchaV3) => this._captchaRef = ref}

                    captchaDomain   ={'...'}
                    siteKey         ={'...'}
                    onReceiveToken={(_token: string) =>
                    {
                        Alert.alert('CAPTCHA', _token);
                        console.log(_token);
                    }}/>
            </>
```
How I can find out what happens, what problem? Do you have error props? like **onError**?
BTW **this._captchaRef** is not null

**Comment by Haskkor** [comment]
Hi!

Is a captcha logged?
Do you see a request coming out if you inspect the network?

**Comment by DenisSokoloff** [comment]
I try Telerik to inspect tracffic, but I did not see any requests, and _captchaRef was initialized

**Comment by Haskkor** [comment]
I'm struggling with this one...
I don't understand what can go wrong. Is the Webview ok? Can you use it to display smthg else?

**Comment by DenisSokoloff** [comment]
I wrote self GoogleCaptcha3, with Webview, like your,  I tested it on Android device, works ok! 
Why your code did not return token, I did not understand, but I think issue can be closed, 
Thanks for your code, Good Luck

**Comment by agarwalnitesh** [comment]
@DenisSokoloff Can you please share your own written code of GoogleCaptcha3 to fix these issues?

**Comment by DenisSokoloff** [comment]
> @DenisSokoloff Can you please share your own written code of GoogleCaptcha3 to fix these issues?

https://github.com/DenisSokoloff/GoogleReCaptchaWebView

**Comment by agarwalnitesh** [comment]
> > @DenisSokoloff Can you please share your own written code of GoogleCaptcha3 to fix these issues?
> 
> https://github.com/DenisSokoloff/GoogleReCaptchaWebView

@DenisSokoloff Thanks for your quick response but still after using this I'm unable to fetch the token.

 <GoogleReCaptchaWebView 
captchaDomain={'com.android.xyz'}
                    
siteKey={'xyx'} 
/>

Can you please help me to get the token?

**Comment by DenisSokoloff** [comment]
Updated https://github.com/DenisSokoloff/GoogleReCaptchaWebView

**Comment by agarwalnitesh** [comment]
> Updated https://github.com/DenisSokoloff/GoogleReCaptchaWebView
what should be the GOOGLE_CAPTCHA_DOMAIN for mobile App because I'm using Android bundle identifier as a domain name in google Recaptcha dashboard and then getting an error 
"ERROR for site owner: Invalid domain for site key".

Can you please suggest how we get the domain name for mobile?

**Comment by DenisSokoloff** [comment]
I use Google Captcha on site and in mobile APP
I setuped Google Captcha for my domain and use this domain in APP too
**baseUrl** - same how my domain in **WebView**

```
 source={
                                            {
                                                html: html,
                                                baseUrl: url
                                            }}
```

If you do not have domain, you can setup localhost
