### ISSUE TITLE
onReceiveToken not working

### ISSUE THREAD

**Issue by andrewyohanes123** [jarden-digital/react-native-recaptchav3#5]
The `onReceiveToken` is not invoke. I even try using ref and button to reload the token but it doesn't work.

here's my code
`<ReCaptchaV3
              captchaDomain={'http://mysite.com'}
              siteKey={'token'}
              onReceiveToken={token => alert(token)}
              ref={ref => this.captcha = ref}
            />
<Button onPress={() => this.captcha.refreshToken()}><Text>Press</Text></Button>`

I'm using react native v0.61.1 and react v.16.9.0

**Comment by Haskkor** [comment]
Thanks for that.
I found the issue I'll be releasing a new version in a few minutes.
Sorry for the delay.
