### ISSUE TITLE
On calling refreshToken()  returns undefined

### ISSUE THREAD

**Issue by srajesh636** [jarden-digital/react-native-recaptchav3#6]

**Comment by codebymani** [comment]
refreshToken() returns "null" for me in ios
@srajesh636 did you find any workaround?

**Comment by bockc** [comment]
Same for me, and it does not trigger the `onReceiveToken` callback, so no recaptcha token for iOS.....

EDIT: found out that for the `captchaDomain` you have to set `captchaDomain="https://com.package.name"`, simply putting your package name like `captchaDomain="com.package.name"` won't work
