### ISSUE TITLE
Tried to register two views with the same name RNCWebView

### ISSUE THREAD

**Issue by agarwalnitesh** [jarden-digital/react-native-recaptchav3#9]
Issue Description
I'm already depending on react-native-webview  and when I add @haskkor/react-native-recaptchav3 I'm getting this error: Tried to register two views with the same name RNCWebView

1. I already try to match the version of react-native-webview in my project package.json and package.json of @haskkor/react-native-recaptchav3 but it didn't work

MyProjectPackage.json
{
  "dependencies": {
    "react-native-webview": "9.0.1",
    "@haskkor/react-native-recaptchav3": "1.2.0",
  }
}
and
@haskkor/react-native-recaptchav3 package.json

{
  "dependencies": {
    "react-native-webview": "9.0.1",
  }
}

2. I had also try npm cache clean --force and rm -rf node_modules && npm install but didn't get any success.

Please suggest Any fix!!

**Comment by agarwalnitesh** [comment]
I can fix this issue by removing react-native-webview from package.json dependencies of @haskkor/react-native-recaptchav3.

But stuck in other issue where I'm unable to get the token, also after using  this._captchaRef.refreshToken() getting undefined.

**Comment by Vednus** [comment]
I don't think removing the dependency from this package is the best method. Could we upgrade the dependency to 10?

**Comment by amitkumarcoding** [comment]
This issue is because this library itself has a dependency on react-native-webview version 9.0.1. I have fixed this issue by updating react-native-webview to version 11.18.1.
